# Generated by Django 5.2.1 on 2025-07-24 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_advertisement', models.BooleanField(default=False)),
                ('ad_interval', models.PositiveIntegerField(blank=True, help_text='Advertisement interval in seconds', null=True)),
                ('ticker_enabled', models.BooleanField(default=False)),
                ('ticker_text', models.TextField(blank=True)),
                ('ticker_speed', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('repeat_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.layout')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=10, help_text='Duration in seconds')),
                ('zone', models.CharField(default='main', help_text='Layout zone (main, side, bottom, etc.)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fullscreen', models.BooleanField(default=False)),
                ('transition_effect', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], default='none', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.asset')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
            ],
            options={
                'verbose_name': 'Playlist Item',
                'verbose_name_plural': 'Playlist Items',
                'ordering': ['order'],
                'unique_together': {('playlist', 'asset', 'zone')},
            },
        ),
    ]
