# Generated by Django 5.2.1 on 2025-07-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_hardware_info_remove_player_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_timestamp', models.DateTimeField(help_text='Timestamp from the device (may differ from server time)')),
                ('level', models.CharField(choices=[('VERBOSE', 'Verbose'), ('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('SYNC', 'Synchronization'), ('PLAYBACK', 'Playback'), ('NETWORK', 'Network'), ('STORAGE', 'Storage'), ('UI', 'User Interface'), ('HARDWARE', 'Hardware'), ('APP', 'Application')], default='APP', max_length=15)),
                ('tag', models.CharField(help_text='Log tag (like Android Log.tag)', max_length=50)),
                ('message', models.TextField(help_text='Log message content')),
                ('thread_name', models.CharField(blank=True, max_length=50)),
                ('method_name', models.CharField(blank=True, max_length=100)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('exception_class', models.CharField(blank=True, max_length=100)),
                ('stack_trace', models.TextField(blank=True)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_available_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='players.player')),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'ordering': ['-device_timestamp', '-timestamp'],
                'indexes': [models.Index(fields=['player', '-device_timestamp'], name='players_dev_player__2a1c4f_idx'), models.Index(fields=['level', '-device_timestamp'], name='players_dev_level_4702a5_idx'), models.Index(fields=['category', '-device_timestamp'], name='players_dev_categor_cc216f_idx'), models.Index(fields=['tag', '-device_timestamp'], name='players_dev_tag_edd8db_idx')],
            },
        ),
    ]
