# Generated by Django 5.2.1 on 2025-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='system', max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('deploy', 'Deploy'), ('sync', 'Sync'), ('upload', 'Upload'), ('register', 'Register')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_name', models.CharField(default='PiSignage Installation', max_length=200)),
                ('max_file_size_mb', models.PositiveIntegerField(default=500)),
                ('allowed_file_types', models.CharField(default='mp4,avi,mov,jpg,png,pdf,html,zip,mp3', max_length=500)),
                ('auto_convert_videos', models.BooleanField(default=True)),
                ('video_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra', 'Ultra')], default='high', max_length=10)),
                ('generate_thumbnails', models.BooleanField(default=True)),
                ('default_sync_interval', models.PositiveIntegerField(default=300)),
                ('server_name', models.CharField(blank=True, max_length=200)),
                ('server_port', models.PositiveIntegerField(default=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
