# Generated by Django 5.2.1 on 2025-07-24 19:18

import content.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout',
            options={'ordering': ['code'], 'verbose_name': 'Layout', 'verbose_name_plural': 'Layouts'},
        ),
        migrations.AddField(
            model_name='asset',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum of file', max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata like codec, bitrate, fps, etc.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='layout',
            name='code',
            field=models.CharField(choices=[('1', 'Layout 1 - Full Screen'), ('2a', 'Layout 2a - Main + Side'), ('2b', 'Layout 2b - Main + Bottom'), ('3a', 'Layout 3a - Main + 2 Sides'), ('3b', 'Layout 3b - Main + Side + Bottom'), ('4', 'Layout 4 - 4 Quadrants'), ('4b', 'Layout 4b - Main + 3 Zones'), ('2ab', 'Layout 2ab - Main + Side + Bottom'), ('custom', 'Custom Layout')], default='1', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Custom HTML template for layout (for custom layouts only)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('pdf', 'PDF'), ('html', 'HTML'), ('zip', 'ZIP Package'), ('link', 'Web Link'), ('rss', 'RSS Feed'), ('calendar', 'Google Calendar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=content.models.asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'jpg', 'jpeg', 'png', 'gif', 'pdf', 'html', 'zip', 'mp3', 'wav', 'aac'])]),
        ),
        migrations.AlterField(
            model_name='layout',
            name='zones_config',
            field=models.JSONField(default=dict, help_text='JSON configuration defining layout zones and their properties'),
        ),
        migrations.CreateModel(
            name='AssetConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('conversion_type', models.CharField(choices=[('video_mp4', 'Video to MP4'), ('thumbnail', 'Thumbnail Generation'), ('metadata', 'Metadata Extraction')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='content.asset')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
